### ISSUE TITLE
J'ai un problème quand je met les fichiers tel quel sur mon serveur

### ISSUE THREAD

**Issue by Lulukill3r11** [syroneV/syr-pausemenuv2#1]
Bonjour,

Je viens vers vous car dès que je me connecte à mon serveur j'ai le menu échap qui se lance tout seul obligé de le quitté à chaque connexion 
ensuite j'ai un code d'erreur quand je clique sur les boutons du menu 
et j'ai le bouton report qui ne fonctionne pas 
et j'ai le fond du menu noir au lieux d'avoir mon écran de jeu flouté
alors que j'ai mit les fichiers tel quel

![image](https://user-images.githubusercontent.com/132913066/236833450-7f7e3938-78a4-4959-abb4-db7c42b1d9b2.png)

Pouvez vous m'aider svp ?

Cordialement,

Lulukill3r11

**Comment by 0xS4cha** [comment]
Salut, ceci est causé par le fait que j'ai utilisé l'une de mes anciennes pauses, je vais commit le corriger dans 5min
